## Import Data

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv('data-latihan-kotor.csv')

df

,id,nama_pelanggan,kota,produk,kategori,harga,jumlah,tanggal_pembelian
0,1,Andi,Jakarta,Laptop,Elektronik,15000000.0,1,2024-01-05
1,2,Budi,Bandung,Mouse,Elektronik,150000.0,2,05/01/2024
2,3,Siti,jakarta,Keyboard,Elektronik,300000.0,1,2024-01-07
3,4,Rina,Surabaya,Meja,Furniture,1200000.0,1,07-01-2024
4,5,Dedi,Bandung,Kursi,Furniture,700000.0,2,2024-01-08
5,6,Andi,Jakarta,Laptop,Elektronik,15000000.0,1,2024-01-05
6,7,Lina,Jakarta,Monitor,Elektronik,NaN,1,2024-01-09
7,8,Rudi,Surabaya,Mouse,Elektronik,150000.0,-1,2024-01-10
8,9,Tono,Bandung,Keyboard,Elektronik,300000.0,2,10/01/2024
9,10,Sari,NaN,Laptop,Elektronik,14000000.0,1,2024-01-11
10,11,Budi,Bandung,Mouse,Elektronik,150000.0,2,2024-01-05
11,12,Dewi,Jakarta,Meja,Furniture,1200000.0,1,2024-01-12
12,13,Asep,Bandung,Kursi,Furniture,700000.0,1,2024-01-13
13,14,Rina,Surabaya,Kursi,Furniture,700000.0,1,13-01-2024
14,15,Fajar,Jakarta,Laptop,Elektronik,16000000.0,1,2024-01-14

In [7]:
# Analisisi Dasar

print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

   id nama_pelanggan      kota    produk    kategori       harga  jumlah  \
0   1           Andi   Jakarta    Laptop  Elektronik  15000000.0       1
1   2          Budi    Bandung     Mouse  Elektronik    150000.0       2
2   3           Siti   jakarta  Keyboard  Elektronik    300000.0       1
3   4           Rina  Surabaya      Meja   Furniture   1200000.0       1
4   5           Dedi   Bandung     Kursi   Furniture    700000.0       2

  tanggal_pembelian
0        2024-01-05
1        05/01/2024
2        2024-01-07
3        07-01-2024
4        2024-01-08
    id nama_pelanggan      kota  produk    kategori       harga  jumlah  \
10  11           Budi   Bandung   Mouse  Elektronik    150000.0       2
11  12           Dewi   Jakarta    Meja   Furniture   1200000.0       1
12  13           Asep   Bandung   Kursi   Furniture    700000.0       1
13  14           Rina  Surabaya   Kursi   Furniture    700000.0       1
14  15          Fajar   Jakarta  Laptop  Elektronik  16000000.0       1

   tanggal_pembelian
10        2024-01-05
11        2024-01-12
12        2024-01-13
13        13-01-2024
14        2024-01-14
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 15 non-null     int64
 1   nama_pelanggan     15 non-null     object
 2   kota               15 non-null     object
 3   produk             15 non-null     object
 4   kategori           15 non-null     object
 5   harga              15 non-null     float64
 6   jumlah             15 non-null     int64
 7   tanggal_pembelian  15 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.1+ KB
None
              id         harga     jumlah
count  15.000000  1.500000e+01  15.000000
mean    8.000000  4.682143e+06   1.133333
std     4.472136  6.544807e+06   0.743223
min     1.000000  1.500000e+05  -1.000000
25%     4.500000  3.000000e+05   1.000000
50%     8.000000  7.000000e+05   1.000000
75%    11.500000  9.341071e+06   1.500000
max    15.000000  1.600000e+07   2.000000

In [30]:
# Data Cleaning

## Mengisi Missing Value
df["kota"] = df["kota"].fillna(df["kota"].iloc[0])
df["harga"] = df["harga"].fillna(df["harga"].mean())

## Membenarkan Format Tanggal
df["tanggal_pembelian"] = pd.to_datetime(
    df["tanggal_pembelian"],
    format="mixed",
    dayfirst=True
)

## Membenarkan Hasil Yang Minus
df = df[df["jumlah"] > 0]

## Menyamakan Format Kota
df["kota"] = df["kota"].str.title().str.strip()

In [ ]:
## Membenarkan Format Harga

pd.options.display.float_format = '{:,.0f}'.format
df

,id,nama_pelanggan,kota,produk,kategori,harga,jumlah,tanggal_pembelian
0,1,Andi,Jakarta,Laptop,Elektronik,"15,000,000",1,2024-01-05
1,2,Budi,Bandung,Mouse,Elektronik,"150,000",2,2024-01-05
2,3,Siti,Jakarta,Keyboard,Elektronik,"300,000",1,2024-01-07
3,4,Rina,Surabaya,Meja,Furniture,"1,200,000",1,2024-01-07
4,5,Dedi,Bandung,Kursi,Furniture,"700,000",2,2024-01-08
5,6,Andi,Jakarta,Laptop,Elektronik,"15,000,000",1,2024-01-05
6,7,Lina,Jakarta,Monitor,Elektronik,"4,682,143",1,2024-01-09
8,9,Tono,Bandung,Keyboard,Elektronik,"300,000",2,2024-01-10
9,10,Sari,Jakarta,Laptop,Elektronik,"14,000,000",1,2024-01-11
10,11,Budi,Bandung,Mouse,Elektronik,"150,000",2,2024-01-05
11,12,Dewi,Jakarta,Meja,Furniture,"1,200,000",1,2024-01-12
12,13,Asep,Bandung,Kursi,Furniture,"700,000",1,2024-01-13
13,14,Rina,Surabaya,Kursi,Furniture,"700,000",1,2024-01-13
14,15,Fajar,Jakarta,Laptop,Elektronik,"16,000,000",1,2024-01-14

In [38]:
# Feature Engineering

## Membuat Kolom Revenue
df["revenue"] = df["harga"] * df["jumlah"]

## Membuat Kolom Bulan
df["bulan"] = df["tanggal_pembelian"].dt.month_name()

## Membuat Kolom Tahun
df["tahun"] = df["tanggal_pembelian"].dt.year

## Membuat Kolom Hari
df["hari"] = df["tanggal_pembelian"].dt.day_name()

df.to_csv("data-latihan-bersih", index=False)